baseURL = "https://vvasuki.github.io/mImAMsA/"
languageCode = "en-us"
title = "मीमांसायां विश्वासटिप्पन्यः"
theme = "sanskrit-documentation-theme-hugo"
publishDir = "build_github"
disablePathToLower = true

[params]
  githubEditMePathBase = "https://github.com/vvasuki/mImAMsA/edit/master/content/"
  contactLink = "https://github.com/vvasuki/mImAMsA/issues/new"
  env = "production"
  disqusShortcode = "vvasuki-site"

[outputs]
  home = ["HTML", "RSS", "JSON", "CSV"]
  section = ["HTML", "RSS", "JSON"]

[markup.goldmark.renderer]
  unsafe= true